import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f4f3f8",
        "primary-fixed": "#f0ecff",
        "secondary-fixed": "#d9f6fa",
        "on-tertiary-container": "#ffffff",
        "on-tertiary-fixed-variant": "#5236c9",
        "primary-fixed-dim": "#dcd6ff",
        "on-primary-container": "#ffffff",
        "outline-variant": "#e9e8f1",
        "surface-container-high": "#efedf6",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#e9e6f1",
        "on-background": "#182034",
        "surface-container-highest": "#e6e3f0",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#f0ecff",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#8b5cff",
        "tertiary-fixed-dim": "#dcd6ff",
        "surface-variant": "#f0eef6",
        "surface-container": "#f7f6fb",
        "on-primary": "#ffffff",
        "secondary": "#43c8d9",
        "surface-bright": "#ffffff",
        "on-primary-fixed": "#2a1a6e",
        "on-secondary-fixed": "#003741",
        "secondary-container": "#d9f6fa",
        "surface-tint": "#6847f5",
        "on-primary-fixed-variant": "#5236c9",
        "tertiary": "#6847f5",
        "background": "#f7f6fb",
        "inverse-on-surface": "#ffffff",
        "on-error": "#ffffff",
        "primary-container": "#8b5cff",
        "inverse-surface": "#242033",
        "inverse-primary": "#dcd6ff",
        "on-secondary-container": "#1a6b78",
        "on-surface": "#182034",
        "error": "#df5d67",
        "surface": "#f7f6fb",
        "on-tertiary-fixed": "#2a1a6e",
        "on-surface-variant": "#70778d",
        "primary": "#6847f5",
        "error-container": "#fdecec",
        "on-error-container": "#a13c48",
        "outline": "#9ba1b2",
        "secondary-fixed-dim": "#a9e9f0",
        "on-secondary-fixed-variant": "#1a6b78"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.25rem",
        gutter: "1.25rem",
        "gutter-mobile": "0.75rem",
        margin: "2rem",
        "margin-mobile": "1rem"
      },
      fontSize: {
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" }]
      },
      fontFamily: {
        "display-lg": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "body-md": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-sm": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "body-sm": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-md": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "label-sm": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "label-md": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-lg": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "label-lg": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "body-lg": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"]
      },
    },
  },
  plugins: [],
};
export default config;
