import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#eff4ff",
        "primary-fixed": "#e1e0ff",
        "secondary-fixed": "#89f5e7",
        "on-tertiary-container": "#fffbff",
        "on-tertiary-fixed-variant": "#5516be",
        "primary-fixed-dim": "#c0c1ff",
        "on-primary-container": "#fffbff",
        "outline-variant": "#c7c4d7",
        "surface-container-high": "#dce9ff",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#ccdbf3",
        "on-background": "#0d1c2e",
        "surface-container-highest": "#d5e3fc",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#e9ddff",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#8455ef",
        "tertiary-fixed-dim": "#d0bcff",
        "surface-variant": "#d5e3fc",
        "surface-container": "#e6eeff",
        "on-primary": "#ffffff",
        "secondary": "#006a61",
        "surface-bright": "#f8f9ff",
        "on-primary-fixed": "#07006c",
        "on-secondary-fixed": "#00201d",
        "secondary-container": "#86f2e4",
        "surface-tint": "#494bd6",
        "on-primary-fixed-variant": "#2f2ebe",
        "tertiary": "#6b38d4",
        "background": "#f8f9ff",
        "inverse-on-surface": "#eaf1ff",
        "on-error": "#ffffff",
        "primary-container": "#6063ee",
        "inverse-surface": "#233144",
        "inverse-primary": "#c0c1ff",
        "on-secondary-container": "#006f66",
        "on-surface": "#0d1c2e",
        "error": "#ba1a1a",
        "surface": "#f8f9ff",
        "on-tertiary-fixed": "#23005c",
        "on-surface-variant": "#464554",
        "primary": "#4648d4",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "outline": "#767586",
        "secondary-fixed-dim": "#6bd8cb",
        "on-secondary-fixed-variant": "#005049"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.25rem",
        gutter: "1.25rem",
        "gutter-mobile": "0.75rem",
        margin: "2rem",
        "margin-mobile": "1rem"
      },
      fontSize: {
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" }]
      },
      fontFamily: {
        "display-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "label-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"]
      },
    },
  },
  plugins: [],
};
export default config;
